/* Generated By:JavaCC: Do not edit this line. LughatDadConstants.java */
package LughatDad;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LughatDadConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MUTA_GHAYYER = 5;
  /** RegularExpression Id. */
  int ITBA3 = 6;
  /** RegularExpression Id. */
  int ETHA = 7;
  /** RegularExpression Id. */
  int WA_ELLA = 8;
  /** RegularExpression Id. */
  int BAYNAMA = 9;
  /** RegularExpression Id. */
  int SAH = 10;
  /** RegularExpression Id. */
  int KHATA = 11;
  /** RegularExpression Id. */
  int KARREER = 12;
  /** RegularExpression Id. */
  int IDENTIFIER = 13;
  /** RegularExpression Id. */
  int NUMBER = 14;
  /** RegularExpression Id. */
  int STRING = 15;
  /** RegularExpression Id. */
  int SC = 16;
  /** RegularExpression Id. */
  int LP = 17;
  /** RegularExpression Id. */
  int RP = 18;
  /** RegularExpression Id. */
  int LB = 19;
  /** RegularExpression Id. */
  int RB = 20;
  /** RegularExpression Id. */
  int PLUS = 21;
  /** RegularExpression Id. */
  int MINUS = 22;
  /** RegularExpression Id. */
  int MULTIPLY = 23;
  /** RegularExpression Id. */
  int DIVIDE = 24;
  /** RegularExpression Id. */
  int GT = 25;
  /** RegularExpression Id. */
  int LT = 26;
  /** RegularExpression Id. */
  int EQ = 27;
  /** RegularExpression Id. */
  int NEQ = 28;
  /** RegularExpression Id. */
  int GE = 29;
  /** RegularExpression Id. */
  int LE = 30;
  /** RegularExpression Id. */
  int ASSIGN = 31;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\u0645\\u062a\\u063a\\u064a\\u0631\"",
    "\"\\u0627\\u0637\\u0628\\u0639\"",
    "\"\\u0625\\u0630\\u0627\"",
    "\"\\u0648\\u0625\\u0644\\u0627\"",
    "\"\\u0628\\u064a\\u0646\\u0645\\u0627\"",
    "\"\\u0635\\u062d\"",
    "\"\\u062e\\u0637\\u0623\"",
    "\"\\u0643\\u0631\\u0631\"",
    "<IDENTIFIER>",
    "<NUMBER>",
    "<STRING>",
    "<SC>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"!=\"",
    "\">=\"",
    "\"<=\"",
    "\"=\"",
  };

}
